### ISSUE TITLE
Print with speaker notes

### ISSUE THREAD

**Issue by mgeisler** [google/comprehensive-rust#1047]
### Discussed in https://github.com/google/comprehensive-rust/discussions/1041

<div type='discussions-op-text'>

<sup>Originally posted by **armenic** July 30, 2023</sup>
Dear developers, community,

Is there a way to print the book with the speaker notes open? When I click print book icon then the pages are rendered with speakers notes appearing as a collapsed `Details >` and it is not clickable in the PDF. It seems one needs to go page by page expand each speaker note so that they are printed.

Thanks so much for your help!</div>

**Comment by sakex** [comment]
I have some time to do this now, I'm assigning myself

**Comment by sakex** [comment]
- I was not able to reproduce locally either with `mdbook serve` or `mdbook build` -> `python3 -m http.server 8080`.
- On the  public version, the first `details` seemed to be opened while the rest are closed.
- At first I thought it was a race condition issue. The actual culprit is actually is that we are checking for `window.location.pathname == "/print.html"` when the actual page in prod is `comprehensive-rust/print.html`. It is easily missed because `mdbook serve` serves directly into `/`.
-  Fix https://github.com/google/comprehensive-rust/pull/1048
