### ISSUE TITLE
Explain binary size in "Small Example"?

### ISSUE THREAD

**Issue by a21152** [google/comprehensive-rust#1493]
It might be worth comparing and explaining (in lecture notes?) the binary size of a "hello world" example built by Rust vs. C.

On Linux, my stripped (strip -s <binary>) version of rust "hello world" is 367K, compared to C's 15K.

**Comment by djmitche** [comment]
Thanks! We actually just took that example out, for a variety of reasons, but basically because it's _way_ too early in the course to be getting into the weeds on issues like that.

I suspect students may sometimes bring up the question of binary size, or it would fit naturally in the bare-metal course. I don't think we need to address it specifically in the fundamentals course.

**Comment by a21152** [comment]
ACK actually optimizing the binary size, e.g. via https://github.com/johnthagen/min-sized-rust, can be tricky. But since the "fundamental" course also serve as a "Rust language" overview, and in the beginning we mention Rust is suited for embedded to servers, and that it does not have a runtime etc. It might still worth briefly mention that Rust is optimized for compilation speed, easy of debugging etc. and the binary size (especially for the hello-world) can be dramatically bigger than that of the of C so to minimize suspension especially for students from embedded space. I will leave that up to you though. Please feel free to close the issue.

**Comment by djmitche** [comment]
Fixed in #1073.
