### ISSUE TITLE
exercises/day-1/for-loops: bonus question solution: pretty_print() too ugly?

### ISSUE THREAD

**Issue by a21152** [google/comprehensive-rust#1495]
I might appreciate it as I learn more about Rust, but it surprised me that Rust can get ugly so quickly.

Do we really need to show (off) this bonus question that early?

**Comment by mgeisler** [comment]
Hi @a21152, it might surprise you, but I also sometimes find Rust very heavy on the syntax... it can be hard to read and understand, even after having used the language for several years.

I think it's because Rust wants to give the programmer very fine control, similar in spirit to how C++ works. Compared to C++, Rust is safer and cleaner, but it's also much younger.

I hope you still enjoy the course — it's been updated substantially since you wrote your comment, so perhaps take a new look :slightly_smiling_face:

**Comment by mgeisler** [comment]
Hi Ali,

For self-study, the existing books do a great job and I highly recommend them! I collected a whole lot of [Other Resources](https://google.github.io/comprehensive-rust/other-resources.html) to help people learn things deeper.

I hope Rust can stay reasonably simple while also fulfilling the goal of being useful in all sorts of environments, from bare-metal to larger servers. The people behind the language are all very smart and considerate people, so I have high hopes that they'll navigate this well :smile:
