### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by ajsobrino700** [google/comprehensive-rust#2045]
Hi, the translation to spanish is not very good, there is some text in english.
Can you improve this?, It is not possible, I could to collaborate in the project and I do some changes :)

**Comment by henrif75** [comment]
Hi @ajsobrino700,
All help is very much appreciated!
This usually happens because translation is tagged as "fuzzy", i.e., when refreshing the translation files the tool we use tried to match one given translation but it wasn't sure it was correct. Those entries are not taking into consideration when the translated pages are rendered.
Please check the TRANSLATIONS.md page for instructions on how to get started and send us your PRs.
