### ISSUE TITLE
GitHub action to check formatting of Markdown files?

### ISSUE THREAD

**Issue by gendx** [google/comprehensive-rust#330]
In https://github.com/google/comprehensive-rust/pull/329, I'm adding some text which makes a line exceed the 80-column standard formatting of markdown files. I'm waiting for the workflows to be approved to see if they will catch the formatting mistake.

If not, it would be good to have a way to automatically format and check the markdown files (ala `cargo fmt` and `cargo fmt --check`).

**Comment by mgeisler** [comment]
Yes, that's definitely something we should add — I'm thinking that we might not need to make it a check for merging (since I want to encourage people to make small drive-by commits). Instead I simply want to reformat things once in a while.

Reformatting everything is waiting on #318 since that will allow us to change the formatting of the Markdown text without affecting the translations.

**Comment by fw-immunant** [comment]
I believe this was fixed by #1157.
