### ISSUE TITLE
Typo in Tuple Structs

### ISSUE THREAD

**Issue by livrth** [google/comprehensive-rust#72]
https://google.github.io/comprehensive-rust/structs/tuple-structs.html

```rust
struct PoundOfForce(f64);
struct Newtons(f64);

fn compute_thruster_force() -> PoundOfForce {
    todo!("Ask a rocket scientist at NASA")
}

fn set_thruster_force(force: Newtons) {
    // ...
}

fn main() {
    let force = compute_thruster_force();
    set_thruster_force(force);
}
```

compile with `cargo run` shows:
```bash
❯ cargo run
   Compiling exercise v0.1.0 (/Users/z/code/exercise)
error[E0308]: mismatched types
  --> src/main.rs:14:24
   |
14 |     set_thruster_force(force);
   |     ------------------ ^^^^^ expected struct `Newtons`, found struct `PoundOfForce`
   |     |
   |     arguments to this function are incorrect
   |
note: function defined here
  --> src/main.rs:8:4
   |
8  | fn set_thruster_force(force: Newtons) {
   |    ^^^^^^^^^^^^^^^^^^ --------------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `exercise` due to previous error
```
So this maybe a typo in the code?

**Comment by mgeisler** [comment]
Hey @livrth,

Thanks for opening the issue! The compilation error is actually intentional: it shows you that Rust found the error in the use of units at compilation time — in the real world, the mistake was found when the [Mars Climate Orbiter crashed into Mars](https://en.wikipedia.org/wiki/Mars_Climate_Orbiter).

I'm working on adding support for speaker notes #53 and then I'll fill in such details on all the pages.

**Comment by livrth** [comment]
> 

Oh I see, thank you very much!
